### ISSUE TITLE
UI : 3D viewer slows down when navigating corpora in Live, but not in Max

### ISSUE THREAD

**Issue by DavidPiazza** [LFO-lab/Mosaique#13]
M2 Max
macOS 14.2.1

**Comment by domthibault** [comment]
@DavidPiazza Je pense que c'est une question de priorité de thread... 

Pas trop certain de ce que je peux faire. Sinon, il faut vérifier si ça fait ça autant lorsque l'on clique que lorsque l'on bouge la caméra. Et à quel nombre de sample ça commence à peser trop lourd.
