### ISSUE TITLE
Ouverture de session Live sauvegardée hasardeuse

### ISSUE THREAD

**Issue by Seulemennt** [LFO-lab/Mosaique#15]
Lorsque j'ouvre une session Live dans lequel il y un corpus sauvegardé, il y a une fenêtre de contexte comme pour sélectionner un dossier qui s'ouvre. Que je fasse annuler ou ok ça ne fait pas de différence, le beach ball se fait aller un peu et ensuite une fenêtre où il est écrit Live avec les bouton OK et Annuler et aucun autre texte. Que je fasse Ok ou Annuler encore une fois ici ça ne change rien. ensuite tout fonctionne.

<img width="1435" alt="Capture d’écran, le 2024-03-11 à 15 23 58" src="https://github.com/LFO-lab/Mosaique/assets/159921675/4c07ba03-15f8-4c5d-a650-795667741757">

<img width="1436" alt="Capture d’écran, le 2024-03-11 à 15 24 36" src="https://github.com/LFO-lab/Mosaique/assets/159921675/79ed8e93-815b-41a7-809c-9049de43799c">

**Comment by domthibault** [comment]
@Seulemennt , as-tu encore le message "Live --- Cancel / OK" qui pop dans la nouvelle version? SI oui, quand est-ce que ça survient? Je ne le vois plus passer maintenant celui-là. Mais c'est p-e ma version...
