### ISSUE TITLE
Transposition des corpus individuels et master transpose contrôlable à partir MIDI keyboard

### ISSUE THREAD

**Issue by Seulemennt** [LFO-lab/Mosaique#17]
Il serait intéressant de pouvoir transposer chacun des corpus individuellement et non seulement un transpose global sur tout le server. Il serait intéressant de pouvoir contrôler le transpose global avec un clavier midi.

**Comment by domthibault** [comment]
Ça, ce sera possible lorsque l'on introduira les "players" qui se connectent au "server". Alors, tu pourras jouer avec les différents corpus de manière indépendante. 

À venir d'ici la fin de l'été.
