### ISSUE TITLE
Temps d'analyse et réduction de dimensions trop longs

### ISSUE THREAD

**Issue by DavidPiazza** [LFO-lab/Mosaique#19]
Pistes de solutions : 
- Ré-échantillonnage à la baisse du buffer d'analyse;
- Ajuster les paramètres par défaut d'analyse et de réduction de dimensions.

**Comment by DavidPiazza** [comment]
- Placer l'analyse dans un poly~ pour downsample n'a pas d'effet sur le temps qu'elle nécessite;
- On peut réduire en moyenne de moitié le temps d'analyse en réduisant le nombre d'itérations au minimum. Jusqu'à maintenant, je ne trouve pas que la saillance de l'analyse et de la classification souffre d'un nombre moins élevé d'itérations (même au minimum de 100).

**Comment by domthibault** [comment]
On a considérablementr améliorer ça avec la version 0.06 qui introduit une meilleure gestion des données (moins de call au disctionnaire) et une analyse sur une durée limitée.

À tester abondamment avec des datasets de durée variable...
