### ISSUE TITLE
Pre-analyzed corpus loading and Live Set recall is too slow

### ISSUE THREAD

**Issue by DavidPiazza** [LFO-lab/Mosaique#39]

**Comment by DavidPiazza** [comment]
Pistes : 
- Corpus multiples avec peu de sons ou bien un corpus avec autant de sons?
- Évaluer et optimiser la logique de rappel des données d'analyse

**Comment by domthibault** [comment]
Loading samples in poly with multithreading. Saved about 10%. Implemented in version 0.1.3
