### ISSUE TITLE
Server parameters should be saved with Live Set

### ISSUE THREAD

**Issue by DavidPiazza** [LFO-lab/Mosaique#6]
Corpus JSON file and path to audio files should be recalled upon loading an Ableton Live Set containing one or more instances of Mosaique

**Comment by domthibault** [comment]
Pain in the butt, we have to maintain a [pattrstorage] as well as enabling the parameter mode of the [dict].

See doc here : https://cycling74.com/forums/automatically-storing-dict's-inside-a-ableton-session-inside-a-max-for-live-device-again

**Comment by domthibault** [comment]
Fixing will be in version 0.05c.

**Comment by domthibault** [comment]
Ok, c'est fonctionnel. Mais au chargement, les sons ne sortent qu'à gauche...
