### ISSUE TITLE
Visualisation 3D - Contrôles disparaissent

### ISSUE THREAD

**Issue by jpjullin** [LFO-lab/Mosaique#7]
Quand j'utilise la fenêtre de visualisation 3D, au bout d'un moment les contrôles affichés sur la fenêtre (move/rotate) disparaissent:
![image](https://github.com/LFO-lab/Mosaique/assets/85247517/c8d70be9-5f96-44b4-a1c0-b6e133296bef)

Parfois il devient impossible de de cliquer ou que ce soit ailleurs que sur cette fenêtre (impossible de cliquer sur un contrôle de live).

Est-ce qu'il y aurait un metro qui force la fenêtre au 1er plan toutes les x ms?

**Comment by domthibault** [comment]
On a enlevé les contrôles dans le GUI 3D
